server:
  port: 8084

spring:
  application:
    name: risk-service
  datasource:
    url: jdbc:h2:mem:onboarding_risk;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: false
      path: /h2-console
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  cache:
    type: simple
  task:
    execution:
      pool:
        core-size: 4
        max-size: 20
        queue-capacity: 200

cache:
  eviction:
    interval-ms: 300000

customer:
  service:
    base-url: http://localhost:8081

account:
  service:
    base-url: http://localhost:8085

notification:
  service:
    base-url: http://localhost:8086

risk:
  high-risk-nationalities:
    - IR
    - KP
    - SY

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html