CREATE TABLE templates (
    template_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    template_key VARCHAR(50) NOT NULL UNIQUE,
    subject VARCHAR(120) NOT NULL,
    content VARCHAR(1000) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
