server:
  port: 8085

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:h2:mem:onboarding_account;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: false
      path: /h2-console
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  cache:
    type: simple
  task:
    execution:
      pool:
        core-size: 4
        max-size: 20
        queue-capacity: 200

customer:
  service:
    base-url: http://localhost:8081

notification:
  service:
    base-url: http://localhost:8086
  
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

cache:
  eviction:
    interval-ms: 300000

core-banking:
  base-url: http://localhost:8090
  default-sort-code: 102030
  mock-enabled: true


resilience4j:
  circuitbreaker:
    instances:
      coreBanking:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
  retry:
    instances:
      coreBanking:
        max-attempts: 3
        wait-duration: 500ms
