spring.datasource.url=jdbc:mysql://localhost:3306/kycdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.cache.type=simple

server.port=8083
server.error.include-message=never

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

customer.service.base-url=http://localhost:8081
document.service.base-url=http://localhost:8082
risk.service.base-url=http://localhost:8084
notification.service.base-url=http://localhost:8086
